### ISSUE TITLE
ImportError: cannot import name 'BertForAceHyperRE' from 'transformers.modeling_bert'

### ISSUE THREAD

**Issue by Deoxyriboncleic-acid** [yanzhh/HGERE#5]
I want to run run_pruner.py, and the following bug occurs
```
Traceback (most recent call last):
  File "run_pruner.py", line 39, in <module>
    from transformers import (WEIGHTS_NAME, BertConfig,
  File "/home/wqy/Work/2024/nlp/HGERE/transformers/src/transformers/__init__.py", line 150, in <module>
    from .modeling_bert import (
ImportError: cannot import name 'BertForAceHyperRE' from 'transformers.modeling_bert' (/home/wqy/Work/2024/nlp/HGERE/transformers/src/transformers/modeling_bert.py)


```
After executing the following command, I found that there is no such code in transformer

```
> cd transformers/src/transformers
> grep -rli "BertForAceHyperRE" .

./__pycache__/__init__.cpython-38.pyc
./__init__.py

```

**Comment by yanzhh** [comment]
Thank you for your reminder.  During my last code update, I removed the code for the class BertForAceHyperRE from the modeling_bert file, as it is no longer needed. However, I forgot to update the \__init\__.py file accordingly, which is causing the load error. You can remove the section of the code containing the text 'BertForAceHyperRE' to solve the problem.
